### ISSUE TITLE
Issue with Raspberry Pi 3b

### ISSUE THREAD

**Issue by Hydro-guy** [vinceskahan/weewx-rtldavis#1]
I realize that this isn't likely an issue with your script.  Only thing I noticed there was I got an error when script installed sqlite - wanted sqlite3.  
I've tried both buster and bullseye - 32 bit and the 64 bit versions and I always get the same error - "Caught WeeWxIOError: rtldavis process stalled"   rtldavis seems to be reading packets correctly but weewx doesnt recognize as a msg and the 150 second loop times out every time.  Hoping you have a suggestion - I did post to the google group user forum but no responses so far.  there is a more extensive log in [https://groups.google.com/d/msgid/weewx-user/95372f12-e423-4732-8a5b-a8dde13c75d7n%40googlegroups.com]

Mar  2 11:00:12 raspberrypi weewx[2529] DEBUG user.rtldavis: Don't store freqErrors for frequency band US
Mar  2 11:00:15 raspberrypi weewx[2529] DEBUG user.rtldavis: info: 11:00:15.449232 8800C8337A009462 14 0 0 0 0 msg.ID=0
Mar  2 11:00:15 raspberrypi weewx[2529] DEBUG user.rtldavis: chan: 11:00:15.449377 Hop: {ChannelIdx:5 ChannelFreq:904928090 FreqError:0 Transmitter:0}
Mar  2 11:00:15 raspberrypi weewx[2529] DEBUG user.rtldavis: Don't store freqErrors for frequency band US
Mar  2 11:00:18 raspberrypi weewx[2529] DEBUG user.rtldavis: info: 11:00:18.011074 9800C800020093E3 15 0 0 0 0 msg.ID=0
Mar  2 11:00:18 raspberrypi weewx[2529] DEBUG user.rtldavis: chan: 11:00:18.011566 Hop: {ChannelIdx:27 ChannelFreq:915966601 FreqError:0 Transmitter:0}
Mar  2 11:00:18 raspberrypi weewx[2529] DEBUG user.rtldavis: Don't store freqErrors for frequency band US
Mar  2 11:00:19 raspberrypi systemd[1]: Starting Cleanup of Temporary Directories...
Mar  2 11:00:19 raspberrypi systemd[1]: systemd-tmpfiles-clean.service: Succeeded.
Mar  2 11:00:19 raspberrypi systemd[1]: Finished Cleanup of Temporary Directories.
Mar  2 11:00:20 raspberrypi weewx[2529] DEBUG user.rtldavis: info: 11:00:20.574039 E800C9800000FDF3 16 0 0 0 0 msg.ID=0
Mar  2 11:00:20 raspberrypi weewx[2529] DEBUG user.rtldavis: chan: 11:00:20.574529 Hop: {ChannelIdx:38 ChannelFreq:921485856 FreqError:0 Transmitter:0}
Mar  2 11:00:20 raspberrypi weewx[2529] DEBUG user.rtldavis: Don't store freqErrors for frequency band US
Mar  2 11:00:23 raspberrypi weewx[2529] DEBUG user.rtldavis: info: 11:00:23.135947 5800C9FF7000FA3F 17 0 0 0 0 msg.ID=0
Mar  2 11:00:23 raspberrypi weewx[2529] INFO weewx.engine: Main loop exiting. Shutting engine down.
Mar  2 11:00:23 raspberrypi weewx[2529] INFO user.rtldavis: shutdown process /home/pi/work/bin/rtldavis -tf US -tr 1
Mar  2 11:00:23 raspberrypi weewx[2529] INFO user.rtldavis: rtldavis with pid 3078 killed
Mar  2 11:00:23 raspberrypi weewx[2529] CRITICAL __main__: Caught WeeWxIOError: rtldavis process stalled
Mar  2 11:00:23 raspberrypi weewx[2529] CRITICAL __main__:     ****  Waiting 60 seconds then retrying...

**Comment by vinceskahan** [comment]
Thanks for the note about sqlite vs sqlite3.  Yes you might find os dependencies as time moves on.  FWIW, I do see sqlite as a valid package on my pi running Raspbian, but yes I'm kinda expecting users to know their os at some level.

No idea about your error.  I don't run the RTL stuff almost ever.  I was just trying to document a howto for folks who wanted to get it working at lesat initially.
